"""Added SaaS credit fields

Revision ID: 4de1ec5ff8c5
Revises: 
Create Date: 2026-04-07 16:51:15.818464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de1ec5ff8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('transcript',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('lecture_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('credits_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_credit_reset', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_credit_reset')
        batch_op.drop_column('credits_remaining')
        batch_op.drop_column('is_pro')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('lecture_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('transcript',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
